#!/usr/bin/env bash

ignored_directories=("./" "./.git")

if ! command -v stow &> /dev/null; then
    echo "Error: 'stow' binary not found. Please install stow before running this script."
    exit 1
fi

git submodule init
git submodule update

packages=($(find ./ -maxdepth 1 -type d))

for package in "${packages[@]}"; do
    if [[ ! " ${ignored_directories[@]} " =~ " $package " ]]; then
        package_name="${package#./}"
        stow -v "$package_name"
    fi
done
