#!/usr/bin/env bash

source packages.sh

if ! command -v stow &> /dev/null; then
    echo "Error: 'stow' binary not found. Please install stow before running this script."
    exit 1
fi

git submodule init
git submodule update

stow_it() {
    stow -v "$1"
}

for_each_package stow_it
